import { 
  Car,
  Building,
  Megaphone,
  ShoppingCart,
  Palette,
  BarChart,
  Crown,
  Home,
  Hotel,
  School,
  Pill,
  Wrench,
  Scissors,
  ChefHat,
  Truck,
  PawPrint,
  Scale,
  Shield,
  Trophy,
  Cake,
  Candy,
  Plane,
  Stethoscope,
  Laptop,
  Sparkles,
  Languages,
  ShieldCheck,
  Zap,
  Armchair,
  Glasses,
  Droplets,
  PartyPopper
} from "lucide-react";

export const products = [
  {
    id: 1,
    name: "🚗 موقع تأجير السيارات الذكي",
    description: "موقع تعريفي متكامل لشركة تأجير سيارات مع نظام حجز ذكي وواجهة مستخدم احترافية وتصميم حصري",
    category: "المواقع التعريفية",
    icon: Car,
    features: [
      "🎨 تصميم احترافي متجاوب ومتحرك",
      "📱 نظام حجز ذكي وتفاعلي",
      "🚙 عرض أسطول السيارات بتقنية ثلاثية الأبعاد",
      "👥 إدارة العملاء والحجوزات",
      "🔒 نظام دفع آمن متكامل",
      "📊 تقارير مالية تفصيلية"
    ],
    price: "5999 ريال",
    rating: 4.9,
    downloads: "145",
    status: "متاح الآن",
    color: "from-blue-500 to-cyan-500",
    demoUrl: "/car-rental-landing",
    tags: ["React", "TypeScript", "Responsive", "AI-Powered"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🚗",
    estimatedDelivery: "15-45 يوم",
    version: "V 1.0"
  },
  {
    id: 2,
    name: "🏗️ موقع شركة المقاولات العالمية",
    description: "موقع تعريفي متكامل لشركة مقاولات عالمية مع عرض احترافي للمشاريع والخدمات وأنيميشن متطور حصري",
    category: "المواقع التعريفية",
    icon: Building,
    features: [
      "🌍 تصميم عالمي احترافي متعدد اللغات",
      "🎞️ عرض المشاريع التفاعلي والمتحرك",
      "✨ أنيميشن متطور وحصري",
      "🗣️ نظام متعدد اللغات (عربي/إنجليزي)",
      "📋 نظام إدارة المحتوى المتقدم",
      "🖼️ معرض أعمال ديناميكي ثلاثي الأبعاد"
    ],
    price: "3599 ريال",
    rating: 5.0,
    downloads: "89",
    status: "متاح الآن",
    color: "from-emerald-500 to-teal-500",
    demoUrl: "/construction-website",
    tags: ["Global", "Construction", "Animated", "3D", "AI-Enhanced"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🏗️",
    estimatedDelivery: "15-45 يوم",
    version: "V 1.0"
  },
  {
    id: 3,
    name: "📈 منصة التسويق الإلكتروني الذكية",
    description: "موقع متخصص في التسويق الإلكتروني والتجارة الرقمية مع أدوات تحليل متقدمة وذكاء اصطناعي",
    category: "التسويق الرقمي",
    icon: Megaphone,
    features: [
      "🤖 أدوات تحليل بالذكاء الاصطناعي",
      "📊 إدارة الحملات الإعلانية الذكية",
      "📱 التسويق عبر وسائل التواصل",
      "🔍 تحليل المنافسين المتقدم",
      "📈 تقارير مفصلة وتفاعلية",
      "💬 دعم فني متخصص على مدار الساعة"
    ],
    price: "3500 ريال",
    rating: 4.9,
    downloads: "234",
    status: "متاح الآن",
    color: "from-purple-500 to-pink-500",
    demoUrl: "/digital-marketing-website",
    tags: ["AI-Powered", "Marketing", "Analytics", "Social Media"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "📈",
    estimatedDelivery: "15-45 يوم",
    version: "V 1.0"
  },
  {
    id: 5,
    name: "👑 متجر عبايتي",
    description: "متجر إلكتروني فاخر ومتكامل للعبايات العصرية مع تصميم عالمي مميز وتكامل مع الواتساب وتجربة تسوق استثنائية",
    category: "التجارة الإلكترونية",
    icon: Crown,
    features: [
      "👑 تصميم فاخر وعالمي حصري",
      "👗 أقسام متنوعة للعبايات العصرية",
      "💬 تكامل مع الواتساب للطلبات",
      "📱 تجربة تسوق متجاوبة 100%",
      "✨ أنيميشن وتأثيرات بصرية متطورة",
      "🏪 إدارة متكاملة للمخزون والطلبات"
    ],
    price: "3999 ريال",
    rating: 5.0,
    downloads: "12",
    status: "متاح الآن",
    color: "from-rose-500 to-pink-600",
    demoUrl: "/abayati-store",
    tags: ["Fashion", "E-commerce", "WhatsApp", "Luxury", "Abaya"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "👑",
    estimatedDelivery: "15-45 يوم",
    version: "V 1.0"
  },
  {
    id: 6,
    name: "🏠 نظام إدارة العقارات",
    description: "نظام متكامل لإدارة العقارات السكنية والتجارية مع تتبع الإيجارات والصيانة",
    category: "الأنظمة الإدارية",
    icon: Home,
    features: [
      "🏘️ إدارة شاملة للعقارات",
      "💰 متابعة الإيجارات والدفعات",
      "🔧 نظام طلبات الصيانة",
      "📊 تقارير مالية تفصيلية",
      "👥 إدارة المستأجرين والعقود",
      "📱 تطبيق موبايل للمستأجرين"
    ],
    price: "4500 ريال",
    rating: 4.9,
    downloads: "67",
    status: "متاح الآن",
    color: "from-amber-500 to-orange-500",
    demoUrl: "#",
    tags: ["Real Estate", "Management", "Rental", "AI-Powered"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🏠",
    estimatedDelivery: "15-30 يوم",
    version: "V 1.0"
  },
  {
    id: 7,
    name: "🏨 نظام إدارة الفنادق الذكي",
    description: "نظام متطور لإدارة الفنادق والمنتجعات مع حجز أونلاين وإدارة الغرف",
    category: "الأنظمة الإدارية",
    icon: Hotel,
    features: [
      "🛏️ إدارة الغرف والحجوزات",
      "💳 نظام دفع آمن متكامل",
      "🍽️ إدارة خدمات الطعام",
      "👔 إدارة الموظفين والنوبات",
      "📈 تقارير الإشغال والإيرادات",
      "🌐 موقع حجز أونلاين"
    ],
    price: "5500 ريال",
    rating: 5.0,
    downloads: "45",
    status: "متاح الآن",
    color: "from-indigo-500 to-purple-500",
    demoUrl: "#",
    tags: ["Hotel", "Booking", "Hospitality", "AI-Enhanced"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🏨",
    estimatedDelivery: "20-35 يوم",
    version: "V 1.0"
  },
  {
    id: 8,
    name: "🎓 نظام إدارة المدارس الشامل",
    description: "منصة تعليمية متكاملة لإدارة المدارس والطلاب والمعلمين",
    category: "الأنظمة الإدارية",
    icon: School,
    features: [
      "📚 إدارة الطلاب والمعلمين",
      "📝 نظام الاختبارات والدرجات",
      "💬 التواصل مع أولياء الأمور",
      "📅 جدول الحصص الذكي",
      "💰 إدارة الرسوم الدراسية",
      "📊 تقارير أكاديمية شاملة"
    ],
    price: "6500 ريال",
    rating: 4.9,
    downloads: "89",
    status: "متاح الآن",
    color: "from-green-500 to-emerald-500",
    demoUrl: "#",
    tags: ["Education", "School", "Student", "AI-Powered"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🎓",
    estimatedDelivery: "25-40 يوم",
    version: "V 1.0"
  },
  {
    id: 9,
    name: "💊 نظام إدارة الصيدليات",
    description: "نظام ذكي لإدارة الصيدليات مع تتبع المخزون والوصفات الطبية",
    category: "الأنظمة الإدارية",
    icon: Pill,
    features: [
      "💊 إدارة المخزون الدوائي",
      "📋 تتبع الوصفات الطبية",
      "⏰ تنبيهات انتهاء الصلاحية",
      "💰 نظام نقاط البيع",
      "📊 تقارير المبيعات",
      "🔔 إشعارات نفاذ الأدوية"
    ],
    price: "4200 ريال",
    rating: 4.8,
    downloads: "73",
    status: "متاح الآن",
    color: "from-teal-500 to-cyan-500",
    demoUrl: "#",
    tags: ["Pharmacy", "Healthcare", "Inventory", "POS"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "💊",
    estimatedDelivery: "15-30 يوم",
    version: "V 1.0"
  },
  {
    id: 10,
    name: "🔧 نظام إدارة ورش السيارات",
    description: "نظام متكامل لإدارة ورش الصيانة وقطع الغيار",
    category: "الأنظمة الإدارية",
    icon: Wrench,
    features: [
      "🚗 إدارة طلبات الصيانة",
      "🛠️ تتبع قطع الغيار",
      "👨‍🔧 إدارة الفنيين والمواعيد",
      "💵 نظام الفواتير والدفع",
      "📊 تقارير الأداء",
      "📱 تطبيق للعملاء"
    ],
    price: "3800 ريال",
    rating: 4.7,
    downloads: "56",
    status: "متاح الآن",
    color: "from-slate-500 to-gray-600",
    demoUrl: "#",
    tags: ["Auto", "Workshop", "Maintenance", "Service"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🔧",
    estimatedDelivery: "15-25 يوم",
    version: "V 1.0"
  },
  {
    id: 11,
    name: "💇 نظام إدارة الصالونات",
    description: "منصة شاملة لإدارة صالونات التجميل والحجوزات",
    category: "الأنظمة الإدارية",
    icon: Scissors,
    features: [
      "📅 نظام حجز المواعيد",
      "💅 إدارة الخدمات والأسعار",
      "👥 قاعدة بيانات العملاء",
      "💰 نظام نقاط البيع",
      "📊 تقارير الأداء اليومية",
      "🎁 برنامج الولاء والعروض"
    ],
    price: "3500 ريال",
    rating: 4.9,
    downloads: "91",
    status: "متاح الآن",
    color: "from-pink-500 to-rose-500",
    demoUrl: "#",
    tags: ["Beauty", "Salon", "Booking", "POS"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "💇",
    estimatedDelivery: "12-25 يوم",
    version: "V 1.0"
  },
  {
    id: 12,
    name: "🍳 نظام المطابخ السحابية",
    description: "نظام متطور لإدارة المطابخ السحابية والتوصيل",
    category: "الأنظمة الإدارية",
    icon: ChefHat,
    features: [
      "🍕 إدارة القائمة والطلبات",
      "🚚 تتبع التوصيل المباشر",
      "👨‍🍳 إدارة المطبخ والطهاة",
      "💳 نظام دفع متعدد",
      "📊 تحليل المبيعات",
      "📱 تطبيق للعملاء"
    ],
    price: "4800 ريال",
    rating: 5.0,
    downloads: "34",
    status: "متاح الآن",
    color: "from-orange-500 to-red-500",
    demoUrl: "#",
    tags: ["Food", "Cloud Kitchen", "Delivery", "Restaurant"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🍳",
    estimatedDelivery: "18-32 يوم",
    version: "V 1.0"
  },
  {
    id: 13,
    name: "📦 نظام شركات الشحن",
    description: "نظام شامل لإدارة عمليات الشحن والتوصيل",
    category: "الأنظمة الإدارية",
    icon: Truck,
    features: [
      "📍 تتبع الشحنات لحظياً",
      "🚚 إدارة السائقين والمركبات",
      "💰 حساب تكاليف الشحن",
      "📊 تقارير الأداء",
      "🔔 إشعارات للعملاء",
      "🗺️ خرائط تفاعلية"
    ],
    price: "5200 ريال",
    rating: 4.8,
    downloads: "62",
    status: "متاح الآن",
    color: "from-blue-600 to-indigo-600",
    demoUrl: "#",
    tags: ["Shipping", "Logistics", "Tracking", "Delivery"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "📦",
    estimatedDelivery: "20-35 يوم",
    version: "V 1.0"
  },
  {
    id: 14,
    name: "🐾 نظام العيادات البيطرية",
    description: "نظام متكامل لإدارة العيادات البيطرية والحيوانات الأليفة",
    category: "الأنظمة الإدارية",
    icon: PawPrint,
    features: [
      "🐕 ملفات الحيوانات الأليفة",
      "📅 حجز المواعيد",
      "💊 إدارة الأدوية والتطعيمات",
      "🏥 السجل الطبي الشامل",
      "💰 الفواتير والمدفوعات",
      "📊 تقارير طبية"
    ],
    price: "4100 ريال",
    rating: 4.9,
    downloads: "48",
    status: "متاح الآن",
    color: "from-emerald-500 to-green-500",
    demoUrl: "#",
    tags: ["Veterinary", "Pets", "Healthcare", "Clinic"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🐾",
    estimatedDelivery: "15-28 يوم",
    version: "V 1.0"
  },
  {
    id: 15,
    name: "⚖️ نظام مكاتب المحاماة",
    description: "منصة قانونية متكاملة لإدارة القضايا والعملاء",
    category: "الأنظمة الإدارية",
    icon: Scale,
    features: [
      "📁 إدارة القضايا والملفات",
      "👥 قاعدة بيانات العملاء",
      "📅 جدول الجلسات",
      "💼 إدارة المستندات القانونية",
      "💰 الفواتير والأتعاب",
      "📊 تقارير الأداء"
    ],
    price: "5800 ريال",
    rating: 5.0,
    downloads: "41",
    status: "متاح الآن",
    color: "from-gray-700 to-slate-800",
    demoUrl: "#",
    tags: ["Legal", "Law", "Cases", "Management"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "⚖️",
    estimatedDelivery: "22-38 يوم",
    version: "V 1.0"
  },
  {
    id: 16,
    name: "🛡️ نظام شركات التأمين",
    description: "نظام ذكي لإدارة بوالص التأمين والمطالبات",
    category: "الأنظمة الإدارية",
    icon: Shield,
    features: [
      "📋 إدارة البوالص",
      "💵 معالجة المطالبات",
      "👥 إدارة العملاء والوكلاء",
      "📊 تحليل المخاطر",
      "💳 نظام الدفع الآمن",
      "📈 تقارير مالية"
    ],
    price: "6200 ريال",
    rating: 4.8,
    downloads: "37",
    status: "متاح الآن",
    color: "from-blue-700 to-cyan-700",
    demoUrl: "#",
    tags: ["Insurance", "Claims", "Policy", "Risk"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🛡️",
    estimatedDelivery: "25-40 يوم",
    version: "V 1.0"
  },
  {
    id: 17,
    name: "🏆 نظام الأكاديميات الرياضية",
    description: "منصة متكاملة لإدارة الأكاديميات والأندية الرياضية",
    category: "الأنظمة الإدارية",
    icon: Trophy,
    features: [
      "⚽ إدارة اللاعبين والمدربين",
      "📅 جدول التدريبات والمباريات",
      "💰 إدارة الاشتراكات",
      "📊 تتبع الأداء الرياضي",
      "🏅 سجل الإنجازات",
      "📱 تطبيق للاعبين"
    ],
    price: "4600 ريال",
    rating: 4.9,
    downloads: "55",
    status: "متاح الآن",
    color: "from-yellow-500 to-amber-500",
    demoUrl: "#",
    tags: ["Sports", "Academy", "Training", "Athletes"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🏆",
    estimatedDelivery: "18-30 يوم",
    version: "V 1.0"
  },
  {
    id: 18,
    name: "🍰 نظام إدارة المخابز",
    description: "نظام ذكي لإدارة المخابز والإنتاج اليومي",
    category: "الأنظمة الإدارية",
    icon: Cake,
    features: [
      "🍞 إدارة الإنتاج اليومي",
      "📦 تتبع المخزون والمواد",
      "💰 نظام نقاط البيع",
      "🚚 إدارة التوصيل",
      "📊 تقارير المبيعات",
      "👨‍🍳 إدارة العمال والنوبات"
    ],
    price: "3600 ريال",
    rating: 4.8,
    downloads: "68",
    status: "متاح الآن",
    color: "from-amber-400 to-orange-400",
    demoUrl: "#",
    tags: ["Bakery", "Production", "POS", "Delivery"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🍰",
    estimatedDelivery: "12-25 يوم",
    version: "V 1.0"
  },
  {
    id: 19,
    name: "🍬 نظام محلات الحلويات",
    description: "منصة شاملة لإدارة محلات الحلويات والطلبات",
    category: "الأنظمة الإدارية",
    icon: Candy,
    features: [
      "🎂 إدارة المنتجات والأصناف",
      "📝 نظام الطلبات المسبقة",
      "💳 نقاط البيع",
      "🎁 إدارة المناسبات",
      "📊 تقارير المبيعات",
      "📱 تطبيق للعملاء"
    ],
    price: "3400 ريال",
    rating: 4.9,
    downloads: "72",
    status: "متاح الآن",
    color: "from-pink-400 to-rose-400",
    demoUrl: "#",
    tags: ["Sweets", "Desserts", "POS", "Orders"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🍬",
    estimatedDelivery: "10-22 يوم",
    version: "V 1.0"
  },
  {
    id: 20,
    name: "✈️ نظام شركات السفر والسياحة",
    description: "نظام متطور لإدارة وكالات السفر والحجوزات",
    category: "الأنظمة الإدارية",
    icon: Plane,
    features: [
      "✈️ حجز الطيران والفنادق",
      "🗺️ إدارة الرحلات السياحية",
      "👥 قاعدة بيانات العملاء",
      "💳 نظام دفع متعدد",
      "📊 تقارير المبيعات",
      "📱 تطبيق للمسافرين"
    ],
    price: "5900 ريال",
    rating: 5.0,
    downloads: "43",
    status: "متاح الآن",
    color: "from-sky-500 to-blue-500",
    demoUrl: "#",
    tags: ["Travel", "Tourism", "Booking", "Agency"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "✈️",
    estimatedDelivery: "22-38 يوم",
    version: "V 1.0"
  },
  {
    id: 21,
    name: "🏥 نظام المراكز الطبية",
    description: "منصة طبية متكاملة لإدارة المراكز الطبية",
    category: "الأنظمة الإدارية",
    icon: Stethoscope,
    features: [
      "👨‍⚕️ إدارة الأطباء والممرضين",
      "📅 نظام الحجوزات",
      "📋 السجلات الطبية",
      "💊 إدارة الصيدلية",
      "💰 الفواتير والتأمين",
      "📊 تقارير طبية شاملة"
    ],
    price: "7200 ريال",
    rating: 5.0,
    downloads: "51",
    status: "متاح الآن",
    color: "from-red-500 to-pink-500",
    demoUrl: "#",
    tags: ["Medical", "Healthcare", "Clinic", "Hospital"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🏥",
    estimatedDelivery: "28-45 يوم",
    version: "V 1.0"
  },
  {
    id: 22,
    name: "💻 نظام محلات الإلكترونيات",
    description: "نظام ذكي لإدارة محلات الإلكترونيات والأجهزة",
    category: "الأنظمة الإدارية",
    icon: Laptop,
    features: [
      "📱 إدارة المنتجات التقنية",
      "🔧 خدمات الصيانة",
      "💰 نظام نقاط البيع",
      "📦 إدارة المخزون",
      "🛡️ الضمانات والكفالات",
      "📊 تقارير المبيعات"
    ],
    price: "4300 ريال",
    rating: 4.8,
    downloads: "59",
    status: "متاح الآن",
    color: "from-indigo-600 to-purple-600",
    demoUrl: "#",
    tags: ["Electronics", "Retail", "POS", "Warranty"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "💻",
    estimatedDelivery: "15-28 يوم",
    version: "V 1.0"
  },
  {
    id: 23,
    name: "✨ نظام شركات التنظيف",
    description: "منصة متكاملة لإدارة شركات التنظيف والعمالة",
    category: "الأنظمة الإدارية",
    icon: Sparkles,
    features: [
      "🧹 إدارة طلبات التنظيف",
      "👷 إدارة العمال والفرق",
      "📅 جدولة المهام",
      "💰 الفواتير والمدفوعات",
      "📊 تقييم الخدمة",
      "📱 تطبيق للعملاء"
    ],
    price: "3900 ريال",
    rating: 4.7,
    downloads: "64",
    status: "متاح الآن",
    color: "from-teal-400 to-cyan-400",
    demoUrl: "#",
    tags: ["Cleaning", "Services", "Booking", "Management"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "✨",
    estimatedDelivery: "14-26 يوم",
    version: "V 1.0"
  },
  {
    id: 24,
    name: "🌐 نظام مراكز الترجمة",
    description: "نظام احترافي لإدارة مكاتب الترجمة والمترجمين",
    category: "الأنظمة الإدارية",
    icon: Languages,
    features: [
      "📄 إدارة طلبات الترجمة",
      "👥 إدارة المترجمين",
      "💰 التسعير والفواتير",
      "📊 تتبع المشاريع",
      "🔍 مراجعة الجودة",
      "📱 بوابة العملاء"
    ],
    price: "4400 ريال",
    rating: 4.9,
    downloads: "46",
    status: "متاح الآن",
    color: "from-violet-500 to-purple-500",
    demoUrl: "#",
    tags: ["Translation", "Languages", "Services", "Management"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🌐",
    estimatedDelivery: "16-30 يوم",
    version: "V 1.0"
  },
  {
    id: 25,
    name: "🛡️ نظام شركات الأمن",
    description: "منصة شاملة لإدارة شركات الحراسة الأمنية",
    category: "الأنظمة الإدارية",
    icon: ShieldCheck,
    features: [
      "👮 إدارة الحراس والنوبات",
      "📍 تتبع الموقع GPS",
      "📊 التقارير اليومية",
      "👥 إدارة العملاء والعقود",
      "💰 الرواتب والمدفوعات",
      "📱 تطبيق للحراس"
    ],
    price: "5100 ريال",
    rating: 4.8,
    downloads: "52",
    status: "متاح الآن",
    color: "from-slate-600 to-gray-700",
    demoUrl: "#",
    tags: ["Security", "Guards", "Management", "Tracking"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🛡️",
    estimatedDelivery: "18-32 يوم",
    version: "V 1.0"
  },
  {
    id: 26,
    name: "⚡ نظام مراكز الليزر التجميلية",
    description: "نظام متطور لإدارة مراكز الليزر والعناية بالبشرة",
    category: "الأنظمة الإدارية",
    icon: Zap,
    features: [
      "💆 إدارة الجلسات والعلاجات",
      "📅 نظام الحجوزات",
      "👥 ملفات العملاء الطبية",
      "💰 الباقات والعروض",
      "📊 تقارير الأداء",
      "🎁 برنامج الولاء"
    ],
    price: "4700 ريال",
    rating: 5.0,
    downloads: "38",
    status: "متاح الآن",
    color: "from-fuchsia-500 to-pink-500",
    demoUrl: "#",
    tags: ["Beauty", "Laser", "Clinic", "Booking"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "⚡",
    estimatedDelivery: "17-30 يوم",
    version: "V 1.0"
  },
  {
    id: 27,
    name: "🛋️ نظام معارض الأثاث",
    description: "منصة متكاملة لإدارة معارض الأثاث والديكور",
    category: "الأنظمة الإدارية",
    icon: Armchair,
    features: [
      "🛋️ إدارة المنتجات والكتالوج",
      "📐 تصاميم 3D تفاعلية",
      "💰 نظام الفواتير",
      "🚚 إدارة التوصيل",
      "📊 تتبع المبيعات",
      "📱 تطبيق للعملاء"
    ],
    price: "4900 ريال",
    rating: 4.9,
    downloads: "47",
    status: "متاح الآن",
    color: "from-brown-500 to-amber-600",
    demoUrl: "#",
    tags: ["Furniture", "Retail", "3D", "Showroom"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🛋️",
    estimatedDelivery: "20-34 يوم",
    version: "V 1.0"
  },
  {
    id: 28,
    name: "👓 نظام محلات النظارات",
    description: "نظام ذكي لإدارة محلات النظارات الطبية والشمسية",
    category: "الأنظمة الإدارية",
    icon: Glasses,
    features: [
      "👓 إدارة المنتجات والماركات",
      "👁️ سجل الفحوصات البصرية",
      "💰 نظام نقاط البيع",
      "📋 تتبع الطلبات الخاصة",
      "📊 تقارير المبيعات",
      "🎁 برنامج العروض"
    ],
    price: "3700 ريال",
    rating: 4.8,
    downloads: "61",
    status: "متاح الآن",
    color: "from-blue-400 to-indigo-400",
    demoUrl: "#",
    tags: ["Optics", "Glasses", "Retail", "POS"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "👓",
    estimatedDelivery: "13-25 يوم",
    version: "V 1.0"
  },
  {
    id: 29,
    name: "💧 نظام مراكز الغسيل الذاتي",
    description: "منصة متطورة لإدارة مراكز غسيل السيارات الذاتية",
    category: "الأنظمة الإدارية",
    icon: Droplets,
    features: [
      "🚗 إدارة المحطات والآلات",
      "💳 نظام دفع إلكتروني",
      "📊 مراقبة الاستخدام",
      "🔧 تنبيهات الصيانة",
      "💰 تقارير الإيرادات",
      "📱 تطبيق للعملاء"
    ],
    price: "4000 ريال",
    rating: 4.7,
    downloads: "54",
    status: "متاح الآن",
    color: "from-cyan-500 to-blue-500",
    demoUrl: "#",
    tags: ["Car Wash", "Self-Service", "Automated", "Payment"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "💧",
    estimatedDelivery: "15-28 يوم",
    version: "V 1.0"
  },
  {
    id: 30,
    name: "🎉 نظام شركات تنظيم الحفلات",
    description: "نظام شامل لإدارة شركات تنظيم المناسبات والحفلات",
    category: "الأنظمة الإدارية",
    icon: PartyPopper,
    features: [
      "🎊 إدارة الفعاليات والحجوزات",
      "🎭 تنسيق الخدمات والموردين",
      "💰 الفواتير والعقود",
      "📅 جدول المناسبات",
      "📊 تقارير مالية",
      "📱 بوابة العملاء"
    ],
    price: "5300 ريال",
    rating: 5.0,
    downloads: "42",
    status: "متاح الآن",
    color: "from-purple-500 to-pink-500",
    demoUrl: "#",
    tags: ["Events", "Parties", "Planning", "Management"],
    isNew: true,
    isFeatured: true,
    isExclusive: true,
    emoji: "🎉",
    estimatedDelivery: "20-35 يوم",
    version: "V 1.0"
  }
];

export const categories = [
  { name: "جميع المنتجات", emoji: "🛍️", count: products.length },
  { name: "المواقع التعريفية", emoji: "🌐", count: 2 },
  { name: "التجارة الإلكترونية", emoji: "🛒", count: 1 },
  { name: "التسويق الرقمي", emoji: "📈", count: 1 },
  { name: "الأنظمة الإدارية", emoji: "⚙️", count: 25 }
];