-- Make order_number nullable so it can be auto-generated by trigger
ALTER TABLE public.product_orders ALTER COLUMN order_number DROP NOT NULL;
ALTER TABLE public.product_orders ALTER COLUMN order_number SET DEFAULT '';

-- Update the unique constraint to handle empty strings properly
ALTER TABLE public.product_orders DROP CONSTRAINT IF EXISTS product_orders_order_number_key;
CREATE UNIQUE INDEX product_orders_order_number_key ON public.product_orders(order_number) 
WHERE order_number IS NOT NULL AND order_number != '';